// Automatically generated by astro-icon
// bd01c67cb31161862634dde3aeb7eb90076e0bd8fc9b6ff92167af6de908e215

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ic:baseline-access-time"
		| "ic:outline-calendar-month";
}